export const metadata = {
  title: "Workout Stuff",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function WorkoutHeader({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
      THIS IS WHERE THE BACK BUTTON GOES
      {children}
    </body>
  );
}
